### ISSUE TITLE
couldn't locate the build.sh file

### ISSUE THREAD

**Issue by adbeda** [conda-forge/cni-feedstock#6]
Issue: Conda build couldn't locate the build.sh file.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/eddiebedada/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0  
absl-py                   0.7.0                    pypi_0    pypi
affine                    2.2.2                    pypi_0    pypi
albumentations            0.2.0                    pypi_0    pypi
altair                    3.1.0                    py36_0    conda-forge
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.6                    py36_0  
appnope                   0.1.0                 py36_1000    conda-forge
argh                      0.26.2                   pypi_0    pypi
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                    pypi_0    pypi
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.7.1                 py36_1001    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
boost-cpp                 1.70.0               hd59e818_0    conda-forge
boto3                     1.9.114                  pypi_0    pypi
botocore                  1.12.114                 pypi_0    pypi
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cachetools                3.1.0                    pypi_0    pypi
cairo                     1.16.0            h0ab9d94_1001    conda-forge
cerberus                  1.1                      pypi_0    pypi
certifi                   2019.3.9                 pypi_0    pypi
cffi                      1.12.3           py36hccf1714_0    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     6.7                      pypi_0    pypi
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                    pypi_0    pypi
cloog                     0.18.0                       10    conda-forge
clyent                    1.2.2                      py_1    conda-forge
conda                     4.7.5                    py36_0    conda-forge
conda-build               3.18.2                   py36_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-forge-pinning       2019.06.19                    0    conda-forge
conda-package-handling    1.3.10                   py36_0    conda-forge
conda-smithy              3.4.0                      py_0    conda-forge
conda-verify              3.1.1                 py36_1000    conda-forge
cryptography              2.7              py36h212c5bf_0    conda-forge
curl                      7.64.1               h22ea746_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.10          py36h6de7cb9_0    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
deprecated                1.2.5                      py_0    conda-forge
descartes                 1.1.0                      py_3    conda-forge
e                         1.4.5                    pypi_0    pypi
earthengine-api           0.1.172                  pypi_0    pypi
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
filelock                  3.0.10                     py_0    conda-forge
fiona                     1.8.4                    pypi_0    pypi
folium                    0.9.1                      py_0    conda-forge
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
future                    0.17.1                py36_1000    conda-forge
gast                      0.2.2                    pypi_0    pypi
gcc                       4.8.5                         8    conda-forge
gdal                      2.4.1            py36h7eb7563_0    conda-forge
geepy                     0.1                      pypi_0    pypi
geographiclib             1.49                       py_0    conda-forge
geojson                   2.3.0                    pypi_0    pypi
geopandas                 0.5.0                      py_2    conda-forge
geopy                     1.20.0                     py_0    conda-forge
geos                      3.7.1             h0a44026_1000    conda-forge
geotiff                   1.4.3             hce09ea4_1000    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.1.7                h01d97ff_1    conda-forge
git                       2.22.0          pl526hbdf3604_0    conda-forge
gitdb2                    2.0.5                      py_0    conda-forge
gitpython                 2.1.11                     py_0    conda-forge
glib                      2.58.3            h9d45998_1001    conda-forge
glob2                     0.7                        py_0    conda-forge
gmp                       5.1.2                         6    conda-forge
google-api-python-client  1.7.8                    pypi_0    pypi
google-auth               1.6.3                    pypi_0    pypi
google-auth-httplib2      0.0.3                    pypi_0    pypi
grpcio                    1.19.0                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h0cbb7df_1106    conda-forge
homura                    0.1.5                    pypi_0    pypi
httplib2                  0.12.1                   pypi_0    pypi
humanize                  0.5.1                    pypi_0    pypi
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.8                      pypi_0    pypi
imgaug                    0.2.6                    pypi_0    pypi
ipykernel                 5.1.1            py36h24bf2e0_0    conda-forge
ipython                   7.5.0            py36h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isl                       0.12.2                        1    conda-forge
isodate                   0.6.0                      py_1    conda-forge
jedi                      0.14.0                   py36_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.6                   py36_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
kealib                    1.4.10            hecf890f_1003    conda-forge
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.7                    pypi_0    pypi
keras-preprocessing       1.0.9                    pypi_0    pypi
kiwisolver                1.1.0            py36h770b8ee_0    conda-forge
krb5                      1.16.3            hcfa6398_1001    conda-forge
label-maker               0.5.1                    pypi_0    pypi
libarchive                3.3.3             h5c473cc_1005    conda-forge
libblas                   3.8.0                7_openblas    conda-forge
libcblas                  3.8.0                7_openblas    conda-forge
libcurl                   7.64.1               h16faf7d_0    conda-forge
libcxx                    8.0.0                         2    conda-forge
libcxxabi                 8.0.0                         2    conda-forge
libdap4                   3.19.1            hae55d67_1000    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgcc                    4.8.5               hdbeacc1_10    conda-forge
libgdal                   2.4.1                h16bfee5_0    conda-forge
libgfortran               3.0.1                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0                7_openblas    conda-forge
liblief                   0.9.0                h2a1bed3_1    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     11.3                 h56406e1_0    conda-forge
libsodium                 1.0.16            h1de35cc_1001    conda-forge
libspatialindex           1.9.0                h6de7cb9_1    conda-forge
libspatialite             4.3.0a            h0cd9627_1026    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                hd80cff7_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
mapbox-vector-tile        1.2.0                    pypi_0    pypi
mapclassify               2.0.1                      py_0    conda-forge
markdown                  3.1.1                    pypi_0    pypi
markupsafe                1.1.1            py36h1de35cc_0    conda-forge
matplotlib                3.1.0                    py36_1    conda-forge
matplotlib-base           3.1.0            py36h3a684a6_1    conda-forge
mbutil                    0.3.0                    pypi_0    pypi
mercantile                1.0.0                    pypi_0    pypi
mistune                   0.8.4           py36h1de35cc_1000    conda-forge
mock                      2.0.0                    pypi_0    pypi
mpc                       1.1.0                         5    conda-forge
mpfr                      4.0.1                         0    conda-forge
msrest                    0.6.8                      py_0    conda-forge
munch                     2.3.2                    pypi_0    pypi
navigator-updater         0.2.1                    py36_0  
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
notebook                  5.7.8                    py36_1    conda-forge
numpy                     1.16.4           py36h6b0580a_0    conda-forge
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.44                     pypi_0    pypi
openblas                  0.3.5             h436c29b_1001    conda-forge
opencv-python             4.0.0.21                 pypi_0    pypi
openjpeg                  2.3.1                hc1feee7_0    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
osmnx                     0.9                        py_1    conda-forge
pandas                    0.24.2           py36h86efe34_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.5.0                      py_0    conda-forge
pathtools                 0.1.2                    pypi_0    pypi
pbr                       5.1.3                    pypi_0    pypi
pcre                      8.41              h0a44026_1003    conda-forge
perl                      5.26.2            haec8ef5_1006    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    4.3.0                    pypi_0    pypi
pip                       19.1.1                   py36_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
poppler                   0.67.0               hb974355_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hf10c77c_0    conda-forge
proj4                     5.2.0             h6de7cb9_1003    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.8.0                    pypi_0    pypi
psutil                    5.6.3            py36h01d97ff_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-lief                   0.9.0            py36h6d6d4d2_1    conda-forge
pyasn1                    0.4.5                    pypi_0    pypi
pyasn1-modules            0.2.4                    pypi_0    pypi
pyclipper                 1.0.6                    pypi_0    pypi
pycosat                   0.6.3           py36h1de35cc_1001    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pycrypto                  2.6.1           py36h1de35cc_1002    conda-forge
pycurl                    7.43.0.1                 pypi_0    pypi
pygeotile                 1.0.6                    pypi_0    pypi
pygithub                  1.43.6                   py36_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyjwt                     1.6.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    1.9.5.1         py36h9c430a6_1007    conda-forge
pyqt                      5.9.2            py36h2a560b1_0    conda-forge
pyrsistent                0.15.2           py36h01d97ff_0    conda-forge
pyshp                     2.1.0                    pypi_0    pypi
pysocks                   1.7.0                    py36_0    conda-forge
python                    3.6.7             h8dc6b48_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-libarchive-c       2.8                   py36_1004    conda-forge
python.app                1.2             py36h1de35cc_1200    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1.1            py36h01d97ff_0    conda-forge
pyzmq                     18.0.1           py36h2d07e9b_1    conda-forge
qt                        5.9.7                h93ee506_2    conda-forge
qtpy                      1.8.0                      py_0    conda-forge
rasterio                  1.0a12                   pypi_0    pypi
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.22.0                   py36_0    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
rio-color                 1.0.0                    pypi_0    pypi
rio-glui                  1.0.6                    pypi_0    pypi
rio-mucho                 1.0.0                    pypi_0    pypi
rio-pansharpen            0.2.0                    pypi_0    pypi
rio-tiler                 1.1.4                    pypi_0    pypi
rio-toa                   0.3.0                    pypi_0    pypi
rsa                       4.0                      pypi_0    pypi
rtree                     0.8.3           py36h666c49c_1002    conda-forge
ruamel                    1.0                      py36_0    conda-forge
ruamel.yaml               0.15.96          py36h01d97ff_0    conda-forge
ruamel_yaml               0.15.71         py36h1de35cc_1000    conda-forge
s3transfer                0.2.0                    pypi_0    pypi
scikit-learn              0.20.3                   pypi_0    pypi
scipy                     1.3.0            py36hab3da7d_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   pypi_0    pypi
shapely                   1.6.4           py36h79c6f3e_1005    conda-forge
shyaml                    0.6.1                    pypi_0    pypi
sip                       4.19.8          py36h0a44026_1000    conda-forge
six                       1.10.0                   pypi_0    pypi
sknw                      0.11                     pypi_0    pypi
smmap2                    2.0.5                      py_0    conda-forge
snuggs                    1.4.3                    pypi_0    pypi
soupsieve                 1.9.2                    py36_0    conda-forge
spacenetutilities         3.0                      pypi_0    pypi
sqlite                    3.28.0               h9721f7c_0    conda-forge
supermercado              0.0.5                    pypi_0    pypi
tensorboard               1.13.0                   pypi_0    pypi
tensorflow                1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.2                    py36_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tilepie                   0.2.1                    pypi_0    pypi
tk                        8.6.9             h2573ce8_1002    conda-forge
toolz                     0.9.0                      py_1    conda-forge
torchsummary              1.5.1                    pypi_0    pypi
tornado                   4.5.3           py36h1de35cc_1001    conda-forge
tqdm                      4.32.2                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
tzcode                    2019a             h01d97ff_1002    conda-forge
uritemplate               3.0.0                    pypi_0    pypi
urllib3                   1.25.3                   pypi_0    pypi
vincent                   0.4.4                      py_1    conda-forge
virtualenv                16.6.0                   pypi_0    pypi
vsts-python-api           0.1.22                     py_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.11.2           py36h01d97ff_0    conda-forge
xerces-c                  3.2.2             h44e365a_1001    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zeromq                    4.3.1             h0a44026_1000    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
active environment : None
       user config file : /Users/eddiebedada/.condarc
 populated config files : /Users/eddiebedada/.condarc
          conda version : 4.7.5
    conda-build version : 3.18.2
         python version : 3.6.7.final.0
       virtual packages : 
       base environment : /Users/eddiebedada/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/eddiebedada/anaconda3/pkgs
                          /Users/eddiebedada/.conda/pkgs
       envs directories : /Users/eddiebedada/anaconda3/envs
                          /Users/eddiebedada/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.22.0 CPython/3.6.7 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
</details>

I've been attempting to update the recipe for this feedstock to the latest version (i.e. `0.7.1`) but the build fails because it couldn't locate the `.build.sh` file.  See the **details** below.
     
```
 /home/conda/feedstock_root/build_artifacts/cni_1561560397323/work/conda_build.sh: line 9: ./build.sh: No such file or directory
```
<details>

```
The following NEW packages will be INSTALLED:

    binutils_impl_linux-64: 2.31.1-h6176602_1   defaults   
    binutils_linux-64:      2.31.1-h6176602_7   defaults   
    gcc_impl_linux-64:      7.3.0-habb00fd_1    conda-forge
    gcc_linux-64:           7.3.0-h553295d_7    conda-forge
    go-nocgo:               1.11.9-h17abafa_0   conda-forge
    go-nocgo_linux-64:      1.11.9-h03773dc_0   conda-forge
    libgcc-ng:              9.1.0-hdf63c60_0    defaults   
    libstdcxx-ng:           9.1.0-hdf63c60_0    defaults   
    make:                   4.2.1-h14c3975_2004 conda-forge

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Source cache directory is: /home/conda/feedstock_root/build_artifacts/src_cache
INFO:conda_build.source:Source cache directory is: /home/conda/feedstock_root/build_artifacts/src_cache
INFO conda_build.source:download_to_cache(43): Source cache directory is: /home/conda/feedstock_root/build_artifacts/src_cache
Found source in cache: cni-0.7.1_4517eabfd6.tar.gz
INFO:conda_build.source:Found source in cache: cni-0.7.1_4517eabfd6.tar.gz
INFO conda_build.source:download_to_cache(63): Found source in cache: cni-0.7.1_4517eabfd6.tar.gz
Extracting download
source tree in: /home/conda/feedstock_root/build_artifacts/cni_1561560397323/work
export PREFIX=/home/conda/feedstock_root/build_artifacts/cni_1561560397323/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho
export BUILD_PREFIX=/home/conda/feedstock_root/build_artifacts/cni_1561560397323/_build_env
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/cni_1561560397323/work
INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-addr2line
+AR=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-ar
+AS=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-as
+CXXFILT=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-c++filt
+ELFEDIT=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-elfedit
+GPROF=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gprof
+HOST=x86_64-conda_cos6-linux-gnu
+LD_GOLD=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-ld.gold
+LD=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-ld
+NM=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-nm
+OBJCOPY=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-objcopy
+OBJDUMP=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-objdump
+RANLIB=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-ranlib
+READELF=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-readelf
+SIZE=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-size
+STRINGS=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-strings
+STRIP=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-strip
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cni-0.7.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+CMAKE_PREFIX_PATH=:$PREFIX:$BUILD_PREFIX/x86_64-conda_cos6-linux-gnu/sysroot/usr
+_CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -I$PREFIX
+CPP=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -ffunction-sections -pipe -I$PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/cni-0.7.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og -I$PREFIX
+GCC_AR=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
+GCC=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc
+GCC_NM=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
+GCC_RANLIB=$BUILD_PREFIX/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,--disable-new-dtags -Wl,--gc-sections -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
/home/conda/feedstock_root/build_artifacts/cni_1561560397323/work/conda_build.sh: line 9: ./build.sh: No such file or directory
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 445, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 436, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2313, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1461, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 397, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 377, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/home/conda/feedstock_root/build_artifacts/cni_1561560397323/work/conda_build.sh']' returned non-zero exit status 1.
```

</details>

However, the `build.sh` file and `meta.yaml` file are kept under the same folder. 
Please find the recipe [here](https://github.com/conda-forge/cni-feedstock/tree/master/recipe)

Any thoughts?

**Comment by adbeda** [comment]
@sodre can you help?

**Comment by scopatz** [comment]
How are you running conda-build?

**Comment by adbeda** [comment]
I was locally testing the build with `CONFIG="linux_" ./.azure/run_docker_build.sh`.

**Comment by sodre** [comment]
going from memory here....
 - cni-feedstock has changed the way they build the binaries. They used to have a build script which was called from our build.sh here https://github.com/conda-forge/cni-feedstock/blob/680989109a2d9e6845a173fb5d5e921d5bbc1aff/recipe/build.sh#L6. But that is no longer available. 
  - The fix is to look at cni's repo and see how the new builds are done and adapt our build.sh.
